apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qbittorrent
  - jellyfin
  - flaresolverr
  - prowlarr
  - radarr
  - sonarr
  - bazarr
  - recyclarr
  - unpackerr
  - seerr
  - shoko
