apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - configmap.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: recyclarr-secrets-yml
    namespace: media
    files:
      - recyclarr.yml=secrets/recyclarr.yml
